authentication/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "authentication"

urlpatterns = [
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("protected", ProtectedView.as_view(), name="protected"),
]

djangoPentaPetra/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "djangoPentaPetra"

urlpatterns = [
    path("auth/", include("authentication.urls")),
    path("", include("pentapetra.urls")),
    path('admin/', admin.site.urls),
]

pentapetra/urls.py
from django.urls import path, include
from pentapetra.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

authentication/models.py
from django.db import models

# Create your models here.

pentapetra/models.py
from django.db import models

authentication/forms.py
from django.forms import forms, CharField, PasswordInput


class LoginForm(forms.Form):
    username = CharField(max_length=100)
    password = CharField(widget=PasswordInput())

authentication/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import AnonymousUser
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View

from authentication.forms import LoginForm


class LoginView(View):
    form_class = LoginForm

    def get(self, req, *args, **kwargs):
        form = self.form_class
        return render(
            req,
            "authentication/login.html",
            {"form": form}
        )

    def post(self, req, *args, **kwargs):
        form = self.form_class(data=req.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(req, username=username, password=password)

            if user is not None:
                login(req, user)
                return HttpResponse("Succesfull")
            else:
                return HttpResponse("Wrong credentials")

        else:
            return HttpResponse("form not valid!")


class LogoutView(View):
    def get(self, req, *args, **kwargs):
        user = req.user
        if isinstance(user, AnonymousUser):
            return HttpResponse("You havent logged in yet.")
        else:
            logout(req)
            return HttpResponse("Logged out")


class ProtectedView(LoginRequiredMixin, View):
    login_url = "login"
    redirect_field_name = "redirect_to"

    def get(self, req, *args, **kwargs):
        user = req.user

        if isinstance(user, AnonymousUser):
            return HttpResponse("Not allowed")

        return HttpResponse("Protected")

pentapetra/views.py
from django.shortcuts import render
from django.views import View


class HomeView(View):

    def get(self, req, *args, **kwargs):
        return render(req, "pentapetra/home.html")

authentication/templates/authentication/login.html
{% extends "base.html" %}

{% block main %}
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Login">
</form>
{% endblock %}

pentapetra/templates/pentapetra/home.html
{% extends "base.html" %}

{% block main %}
HOME
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="../static/base.css">
    <link rel="stylesheet" href="../static/sidemenu.css">
    <title>{% block title %} {% endblock %}</title>
</head>
<body class="flex flex-row">

{% include "navbar.html" %}

<section id="main" class="main" aria-expanded="false">
    {% block main %}
    {% endblock %}
</section>
<script src="../static/sidemenu.js"></script>
</body>
</html>

templates/navbar.html
<section id="sidemenu" class="sidemenu" aria-expanded="false">
    <ul class="text-white">
        {% if user.is_authenticated %}
            <li><a href="{% url "authentication:logout" %}">Logout</a></li>
            <li><a href="{% url "authentication:protected" %}">Protected</a></li>
        {% else %}
            <li><a href="{% url "authentication:login" %}">Login</a></li>
        {% endif %}
    </ul>
</section>

<button id="sidemenu-toggler" class="sidemenu-close-btn lg:hidden">open</button>